[supervisord]
nodaemon=true

[program:postgres]
command=/usr/lib/postgresql/18/bin/postgres -D /var/lib/postgresql/data
user=postgres
autostart=true
autorestart=true

[program:rabbitmq]
command=/usr/sbin/rabbitmq-server
autostart=true
autorestart=true

[program:spring]
command=bash -c "sleep 15 && java -jar /app/app.jar"
autostart=true
autorestart=true